### ISSUE TITLE
[FEAT]: Remove Member From Organization -Backend

### ISSUE THREAD

**Issue by Goldyn19** [Goldyn19/HNG_Issues#4]
### Issue: Implement API To Remove Members from Organization 
**Acceptance Criteria:**

**Acceptance Criteria:**

-Authentication
    -  Only users with sufficient permissions (e.g., team admins) can remove members.
-   Error Handling:
    -   Log errors for invalid requests.

-   Security Measures:
    -   Use HTTPS for secure data transmission.

**Purpose:** To remove members from an organization

**Requirements:**

-   Develop server-side logic to remove members from an organization.
-   Securely store user status details in the database.
-   Ensure compliance with security standards for handling user information.

**Expected Outcome:**

-   The backend should remove members securely and efficiently.
-   The system should log errors and handle invalid requests appropriately.

**Endpoints:**

**Remove User:**

-   **Description:** Remove User.
-   **Endpoint:** `DELETE/api/users`
-   **Request Body:**
  ```
Request Body:
{
 "userId": "string"
 }
```
-   **Response (Success):**
   
  ```
{
 "message": "user deleted successfully",
 "statusCode": 204
}
```
    
-   **Response (Error):**
    
  ```     
  {
  "error": "message"
 "error code": "code"
}
```

**Tasks:**

- [ ]  Create an endpoint `DELETE/api/users` to remove a user from an organization.
- [ ] Implement server-side logic to handle successful and failed remove user requests.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and remove user attempts.
- [ ] Write unit tests for the remove user endpoint.
- [ ] Write integration tests for the  remove user logic.
- [ ] Perform security testing to ensure data protection and compliance.

**Testing:**

-   Write unit tests for backend validation and remove user handling.
-   Write integration tests for the end-to-end remove user process.
-   Perform security testing to ensure data protection and compliance.
-   Test various scenarios for remove user.
