### ISSUE TITLE
[FEAT]: Invite  -Backend

### ISSUE THREAD

**Issue by Goldyn19** [Goldyn19/HNG_Issues#5]
### Issue: Create a backend system for inviting users to organization via email and shareable links.

**Acceptance Criteria:**

• Admins can create invitations with a unique token and expiration date
• Users receive invitation emails with a secure link
• Users can accept invitations and join organisations
• Invitations expire after a set period of time
• Admins can manage (list, revoke, resend) invitations

**Purpose:** To change the role of every organization member and assign privileges

**Requirements:**

-   Develop server-side logic  for inviting users to organization.
-   Securely store user status details in the database.
-   Ensure compliance with security standards for handling user information.

**Expected Outcome:**

• A fully functional invitation system that allows organization admins to invite new members, and users to join organizations through secure, time-limited invitations.

**Endpoints:**

**1. Create Invitation :**

-   **Description:** Create Invitation link.
-   **Endpoint:** `[POST] /api/organisations/{orgId}/invitations`
-   **Request Body:**
  ```
{
 "email": "[user@example.com](mailto:user@example.com)",
 "role": "member"
}
```
-   **Response (Success):**
   
  ```
{
 "message": "Invitation sent successfully",
 "invitation": {
   "id": "inv_123",
   "email": "[johndoe@example.com](mailto:johndoe@example.com)",
   "role": "member",
   "expiresAt": "2023-07-23T00:00:00Z"
 }
}
```
    
-   **Response (Error):**
    
  ```     
  {
  "error": "message"
 "error code": "code"
}
```

**2. Accept Invitation**

-   **Description:** Accept Invitation.
-   **Endpoint:** `[POST]  /api/invitations/accept`
-   **Request Body:**
  ```
{
 "token": "abcdef123456"
}
```
-   **Response (Success):**
   
  ```
{
 "message": "Invitation accepted successfully",
 "organisation": {
   "id": "org_123",
   "name": "My Organisation"
 }
}

```
    
-   **Response (Error):**
    
  ```     
  {
  "error": "message"
 "error code": "code"
}
```

**Tasks:**

- [ ]  Create API for generating invitations
- [ ] Implement email sending for invitations
- [ ]  Create API for accepting invitations
- [ ]  Develop API for managing invitations (list, revoke, resend)

**Testing:**

• Unit tests for invitation creation and acceptance logic
• Integration tests for the end-to-end invitation flow
• Security tests for token generation and validation
